services:
  # PostgreSQL database
  # db:
  #   image: postgres:17
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/postgresql/data  # Persist data in a named volume
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "5432:5432" # Host Port:Container Port

  # Backend Service
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    # depends_on:
    #   - db
    ports:
      - "8000:8000"